// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {library} from '../models';

export function GetFavorites():Promise<Array<string>>;

export function GetGames():Promise<Array<library.Game>>;

export function GetNowPlaying():Promise<Array<library.Session>>;

export function Greet(arg1:string):Promise<string>;

export function Launch(arg1:string):Promise<void>;

export function OpenInstallFolder(arg1:string):Promise<void>;

export function OpenStorePage(arg1:string):Promise<void>;

export function ToggleFavorite(arg1:string):Promise<Array<string>>;
