// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';
import {library} from '../models';
import {friends} from '../models';
import {main} from '../models';
import {epic} from '../models';
import {achievements} from '../models';
import {applog} from '../models';
import {sysmon} from '../models';
import {desktop} from '../models';

export function CheckForUpdates():Promise<update.Status>;

export function ClearLogs():Promise<void>;

export function CreateCollection(arg1:string):Promise<library.Organization>;

export function DeleteCollection(arg1:string):Promise<library.Organization>;

export function DeleteTag(arg1:string):Promise<library.Organization>;

export function DisconnectFriends(arg1:string):Promise<friends.Snapshot>;

export function DisconnectSteamAPI():Promise<main.SteamAPIStatus>;

export function EpicCancelInstall(arg1:string):Promise<void>;

export function EpicCheckUpdates():Promise<Array<epic.UpdateInfo>>;

export function EpicDeletePrefix(arg1:string):Promise<void>;

export function EpicFindImportable():Promise<Array<epic.Importable>>;

export function EpicImport(arg1:string,arg2:string):Promise<void>;

export function EpicImportAll():Promise<number>;

export function EpicInstall(arg1:string):Promise<void>;

export function EpicInstallStates():Promise<Array<epic.Progress>>;

export function EpicLaunchInfo(arg1:string):Promise<epic.LaunchInfo>;

export function EpicLogin(arg1:string):Promise<void>;

export function EpicLoginURL():Promise<string>;

export function EpicLogout():Promise<void>;

export function EpicOpenLogin():Promise<void>;

export function EpicQueue():Promise<epic.QueueState>;

export function EpicQueueMove(arg1:string,arg2:number):Promise<void>;

export function EpicRepair(arg1:string):Promise<void>;

export function EpicSetQueuePaused(arg1:boolean):Promise<void>;

export function EpicSync():Promise<void>;

export function EpicSyncSaves(arg1:string):Promise<void>;

export function EpicUninstall(arg1:string):Promise<void>;

export function EpicUpdate(arg1:string):Promise<void>;

export function EpicUpdates():Promise<Array<epic.UpdateInfo>>;

export function EpicVerify(arg1:string):Promise<void>;

export function GetAchievementOverview():Promise<achievements.Overview>;

export function GetBattlEyeInstall():Promise<epic.ProtonInstallState>;

export function GetBattlEyeRuntime():Promise<epic.BattlEyeRuntime>;

export function GetCardCover(arg1:string):Promise<string>;

export function GetDesktopStatus():Promise<main.DesktopStatus>;

export function GetEpicAccount():Promise<epic.Account>;

export function GetEpicGameSettings(arg1:string):Promise<epic.GameSettings>;

export function GetEpicSettings():Promise<epic.Settings>;

export function GetEpicTools():Promise<epic.Tools>;

export function GetFavorites():Promise<Array<string>>;

export function GetFriends(arg1:boolean):Promise<friends.Snapshot>;

export function GetGameAchievements(arg1:string):Promise<achievements.Detail>;

export function GetGames():Promise<Array<library.Game>>;

export function GetGogAccount():Promise<epic.GogAccount>;

export function GetLegendaryInstall():Promise<epic.ProtonInstallState>;

export function GetLogs():Promise<Array<applog.Line>>;

export function GetNowPlaying():Promise<Array<library.Session>>;

export function GetOrganization():Promise<library.Organization>;

export function GetPlatform():Promise<main.Platform>;

export function GetProtonBuilds():Promise<Array<epic.ProtonBuild>>;

export function GetProtonInstall():Promise<epic.ProtonInstallState>;

export function GetStats(arg1:number):Promise<library.Stats>;

export function GetSteamAPI():Promise<main.SteamAPIStatus>;

export function GetStorage():Promise<main.Storage>;

export function GetUbisoftSetup():Promise<epic.UbisoftSetupState>;

export function GetUbisoftStatus():Promise<epic.UbisoftStatus>;

export function GetUpdateStatus():Promise<update.Status>;

export function GogInstall(arg1:string):Promise<void>;

export function GogLogin(arg1:string):Promise<void>;

export function GogLogout():Promise<void>;

export function GogOpenLogin():Promise<void>;

export function GogSync():Promise<void>;

export function GogUninstall(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function HardwareHistory():Promise<Array<sysmon.Sample>>;

export function HardwareInfo():Promise<sysmon.Info>;

export function HardwareStart():Promise<void>;

export function HardwareStop():Promise<void>;

export function InstallBattlEyeRuntime():Promise<void>;

export function InstallLegendary():Promise<void>;

export function InstallProtonGE():Promise<void>;

export function InstallUpdate():Promise<string>;

export function Launch(arg1:string):Promise<void>;

export function OpenInstallFolder(arg1:string):Promise<void>;

export function OpenLogsFolder():Promise<void>;

export function OpenStorePage(arg1:string):Promise<void>;

export function RenameCollection(arg1:string,arg2:string):Promise<library.Organization>;

export function RestartApp():Promise<void>;

export function SaveShareCard(arg1:string):Promise<string>;

export function ScanAchievements(arg1:boolean):Promise<achievements.Overview>;

export function SetAutoUpdateCheck(arg1:boolean):Promise<update.Status>;

export function SetDesktopSettings(arg1:desktop.Settings):Promise<main.DesktopStatus>;

export function SetEpicGameSettings(arg1:string,arg2:epic.GameSettings):Promise<void>;

export function SetEpicSettings(arg1:epic.Settings):Promise<void>;

export function SetFriendsConfig(arg1:string,arg2:Record<string, string>):Promise<friends.Snapshot>;

export function SetGameCollections(arg1:string,arg2:Array<string>):Promise<library.Organization>;

export function SetGameTags(arg1:string,arg2:Array<string>):Promise<library.Organization>;

export function SetSteamAPIKey(arg1:string):Promise<main.SteamAPIStatus>;

export function SkipUpdate(arg1:string):Promise<update.Status>;

export function ToggleFavorite(arg1:string):Promise<Array<string>>;

export function UbisoftCloseConnect():Promise<void>;

export function UbisoftInstall(arg1:string):Promise<void>;

export function UbisoftInstalling():Promise<Array<epic.UbisoftInstalling>>;

export function UbisoftOpenConnect():Promise<void>;

export function UbisoftReset():Promise<void>;

export function UbisoftSetup():Promise<void>;

export function UbisoftSync():Promise<void>;

export function UbisoftUninstall(arg1:string):Promise<void>;

export function Version():Promise<string>;
