// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function EpicCancelInstall(arg1) {
  return window['go']['main']['App']['EpicCancelInstall'](arg1);
}

export function EpicCheckUpdates() {
  return window['go']['main']['App']['EpicCheckUpdates']();
}

export function EpicDeletePrefix(arg1) {
  return window['go']['main']['App']['EpicDeletePrefix'](arg1);
}

export function EpicFindImportable() {
  return window['go']['main']['App']['EpicFindImportable']();
}

export function EpicImport(arg1, arg2) {
  return window['go']['main']['App']['EpicImport'](arg1, arg2);
}

export function EpicImportAll() {
  return window['go']['main']['App']['EpicImportAll']();
}

export function EpicInstall(arg1) {
  return window['go']['main']['App']['EpicInstall'](arg1);
}

export function EpicInstallStates() {
  return window['go']['main']['App']['EpicInstallStates']();
}

export function EpicLaunchInfo(arg1) {
  return window['go']['main']['App']['EpicLaunchInfo'](arg1);
}

export function EpicLogin(arg1) {
  return window['go']['main']['App']['EpicLogin'](arg1);
}

export function EpicLoginURL() {
  return window['go']['main']['App']['EpicLoginURL']();
}

export function EpicLogout() {
  return window['go']['main']['App']['EpicLogout']();
}

export function EpicOpenLogin() {
  return window['go']['main']['App']['EpicOpenLogin']();
}

export function EpicQueue() {
  return window['go']['main']['App']['EpicQueue']();
}

export function EpicQueueMove(arg1, arg2) {
  return window['go']['main']['App']['EpicQueueMove'](arg1, arg2);
}

export function EpicRepair(arg1) {
  return window['go']['main']['App']['EpicRepair'](arg1);
}

export function EpicSetQueuePaused(arg1) {
  return window['go']['main']['App']['EpicSetQueuePaused'](arg1);
}

export function EpicSync() {
  return window['go']['main']['App']['EpicSync']();
}

export function EpicSyncSaves(arg1) {
  return window['go']['main']['App']['EpicSyncSaves'](arg1);
}

export function EpicUninstall(arg1) {
  return window['go']['main']['App']['EpicUninstall'](arg1);
}

export function EpicUpdate(arg1) {
  return window['go']['main']['App']['EpicUpdate'](arg1);
}

export function EpicUpdates() {
  return window['go']['main']['App']['EpicUpdates']();
}

export function EpicVerify(arg1) {
  return window['go']['main']['App']['EpicVerify'](arg1);
}

export function GetBattlEyeInstall() {
  return window['go']['main']['App']['GetBattlEyeInstall']();
}

export function GetBattlEyeRuntime() {
  return window['go']['main']['App']['GetBattlEyeRuntime']();
}

export function GetEpicAccount() {
  return window['go']['main']['App']['GetEpicAccount']();
}

export function GetEpicGameSettings(arg1) {
  return window['go']['main']['App']['GetEpicGameSettings'](arg1);
}

export function GetEpicSettings() {
  return window['go']['main']['App']['GetEpicSettings']();
}

export function GetEpicTools() {
  return window['go']['main']['App']['GetEpicTools']();
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetGames() {
  return window['go']['main']['App']['GetGames']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetNowPlaying() {
  return window['go']['main']['App']['GetNowPlaying']();
}

export function GetProtonBuilds() {
  return window['go']['main']['App']['GetProtonBuilds']();
}

export function GetProtonInstall() {
  return window['go']['main']['App']['GetProtonInstall']();
}

export function GetStats(arg1) {
  return window['go']['main']['App']['GetStats'](arg1);
}

export function GetStorage() {
  return window['go']['main']['App']['GetStorage']();
}

export function GetUbisoftSetup() {
  return window['go']['main']['App']['GetUbisoftSetup']();
}

export function GetUbisoftStatus() {
  return window['go']['main']['App']['GetUbisoftStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HardwareHistory() {
  return window['go']['main']['App']['HardwareHistory']();
}

export function HardwareInfo() {
  return window['go']['main']['App']['HardwareInfo']();
}

export function HardwareStart() {
  return window['go']['main']['App']['HardwareStart']();
}

export function HardwareStop() {
  return window['go']['main']['App']['HardwareStop']();
}

export function InstallBattlEyeRuntime() {
  return window['go']['main']['App']['InstallBattlEyeRuntime']();
}

export function InstallProtonGE() {
  return window['go']['main']['App']['InstallProtonGE']();
}

export function Launch(arg1) {
  return window['go']['main']['App']['Launch'](arg1);
}

export function OpenInstallFolder(arg1) {
  return window['go']['main']['App']['OpenInstallFolder'](arg1);
}

export function OpenLogsFolder() {
  return window['go']['main']['App']['OpenLogsFolder']();
}

export function OpenStorePage(arg1) {
  return window['go']['main']['App']['OpenStorePage'](arg1);
}

export function SetEpicGameSettings(arg1, arg2) {
  return window['go']['main']['App']['SetEpicGameSettings'](arg1, arg2);
}

export function SetEpicSettings(arg1) {
  return window['go']['main']['App']['SetEpicSettings'](arg1);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function UbisoftCloseConnect() {
  return window['go']['main']['App']['UbisoftCloseConnect']();
}

export function UbisoftInstall(arg1) {
  return window['go']['main']['App']['UbisoftInstall'](arg1);
}

export function UbisoftInstalling() {
  return window['go']['main']['App']['UbisoftInstalling']();
}

export function UbisoftOpenConnect() {
  return window['go']['main']['App']['UbisoftOpenConnect']();
}

export function UbisoftReset() {
  return window['go']['main']['App']['UbisoftReset']();
}

export function UbisoftSetup() {
  return window['go']['main']['App']['UbisoftSetup']();
}

export function UbisoftSync() {
  return window['go']['main']['App']['UbisoftSync']();
}

export function UbisoftUninstall(arg1) {
  return window['go']['main']['App']['UbisoftUninstall'](arg1);
}
