// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EpicCancelInstall(arg1) {
  return window['go']['main']['App']['EpicCancelInstall'](arg1);
}

export function EpicInstall(arg1) {
  return window['go']['main']['App']['EpicInstall'](arg1);
}

export function EpicInstallStates() {
  return window['go']['main']['App']['EpicInstallStates']();
}

export function EpicLaunchInfo(arg1) {
  return window['go']['main']['App']['EpicLaunchInfo'](arg1);
}

export function EpicLogin(arg1) {
  return window['go']['main']['App']['EpicLogin'](arg1);
}

export function EpicLoginURL() {
  return window['go']['main']['App']['EpicLoginURL']();
}

export function EpicLogout() {
  return window['go']['main']['App']['EpicLogout']();
}

export function EpicOpenLogin() {
  return window['go']['main']['App']['EpicOpenLogin']();
}

export function EpicSync() {
  return window['go']['main']['App']['EpicSync']();
}

export function EpicUninstall(arg1) {
  return window['go']['main']['App']['EpicUninstall'](arg1);
}

export function GetEpicAccount() {
  return window['go']['main']['App']['GetEpicAccount']();
}

export function GetEpicSettings() {
  return window['go']['main']['App']['GetEpicSettings']();
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetGames() {
  return window['go']['main']['App']['GetGames']();
}

export function GetNowPlaying() {
  return window['go']['main']['App']['GetNowPlaying']();
}

export function GetProtonBuilds() {
  return window['go']['main']['App']['GetProtonBuilds']();
}

export function GetStats(arg1) {
  return window['go']['main']['App']['GetStats'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Launch(arg1) {
  return window['go']['main']['App']['Launch'](arg1);
}

export function OpenInstallFolder(arg1) {
  return window['go']['main']['App']['OpenInstallFolder'](arg1);
}

export function OpenStorePage(arg1) {
  return window['go']['main']['App']['OpenStorePage'](arg1);
}

export function SetEpicSettings(arg1) {
  return window['go']['main']['App']['SetEpicSettings'](arg1);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}
